---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: molecule/_rules/.yamllint

platforms:
{%- if "6" in cookiecutter.platforms.CentOS %}
  - name: Centos6
    image: lansible/centos:6
{% endif %}

{%- if "wheezy" in cookiecutter.platforms.Debian %}
  - name: Debian7
    image: lansible/debian:7
{% endif %}

{%- if "25" in cookiecutter.platforms.Fedora %}
  - name: Fedora25
    image: lansible/fedora:25
{% endif %}

{%- if "trusty" in cookiecutter.platforms.Ubuntu %}
  - name: Ubuntu1404
    image: lansible/ubuntu:14.04
{% endif %}

{%- if "precise" in cookiecutter.platforms.Ubuntu %}
  - name: Ubuntu1204
    image: lansible/ubuntu:12.04
{%- endif %}

provisioner:
  name: ansible
  options:
    v: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  playbooks:
    create: ../default/create.yml
    prepare: ../default/prepare.yml
    converge: ../default/playbook.yml
    destroy: ../default/destroy.yml
  lint:
    name: ansible-lint
    options:
      c: molecule/_rules/.ansible-lint

scenario:
  name: legacy

verifier:
  name: goss
  enabled: false
