---
dist: trusty
language: python
sudo: required
cache:
  pip: true

install:
  - pip install cookiecutter

script:
  - sudo echo DOCKER_OPTS="-H tcp://127.0.0.1:2375" >> /etc/default/docker
  - sudo service docker restart
  - cookiecutter --no-input .
  - cd role && docker run --net=host -it -v $(pwd):/data/$(basename ~+) -w /data/$(basename ~+) lansible/ansible-dev-container:$TAG molecule converge

notifications:
  email:
    on_failure: change
    on_success: never
