---
dist: trusty
language: minimal
sudo: false

env:
  global:
    - fast_finish: true

services:
  - docker

script:
  - |
    docker run -it -v $(pwd):/data/$(basename ~+) \
    -w /data/$(basename ~+) \
    -e LOCAL_USER_ID=`id -u $USER` \
    -e LOCAL_GROUP_ID=`getent group lxd | cut -d: -f3` \
    lansible/ansible-dev-container:latest \
    molecule init template --url https://github.com/LANsible/ansible-role-skeleton --no-input
  - cd role_name/
  - |
    docker run -it -v $(pwd):/data/$(basename ~+) \
    -w /data/$(basename ~+) \
    -e LOCAL_USER_ID=`id -u $USER` \
    -e LOCAL_GROUP_ID=`getent group lxd | cut -d: -f3` \
    lansible/ansible-dev-container:latest molecule lint

notifications:
  email:
    on_failure: change
    on_success: never
