---
dist: trusty
language: python
sudo: required
cache:
  pip: true

services:
  - docker

addons:
  apt:
    sources:
      - docker-trusty
    packages:
      - docker-ce

install:
  - pip install cookiecutter

before_script:
  - sudo echo DOCKER_OPTS="-H tcp://127.0.0.1:2375" >> /etc/default/docker
  - sudo service docker restart

script:
  - cookiecutter --no-input .
  - docker run --net=host -it -v $(pwd):/data/$(basename ~+) -w /data/$(basename ~+) lansible/ansible-dev-container molecule converge

notifications:
  email:
    on_failure: change
    on_success: never
