---
dist: trusty
language: python
sudo: required
cache:
  pip: true

install:
  - pip install molecule cookiecutter

script:
  - cookiecutter --no-input .
  - cd role && molecule lint

notifications:
  email:
    on_failure: change
    on_success: never
