---

- name: Install prerequisites with apt
  apt:
    name: "{{ role_prerequisites }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install prerequisites with yum
  yum:
    name: "{{ role_prerequisites }}"
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: Install packages for Centos 6 to be able to validate SNI
  yum:
    name: "{{ role_sni_packages }}"
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
