---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
{%- for os, versions in cookiecutter.platforms|dictsort %}
{%- for version in versions %}
{%- if os == "CentOS" and version == "7" %}
  - name: CentOS7
    image: wilmardo/docker-centos-ansible:7
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
{% endif %}

{%- if os == "CentOS" and version == "6" %}
  - name: CentOS6
    image: centos:6
    ulimits:
      - memlock:60397977:60397977
{% endif %}

{%- if os == "Debian" and version == "stretch" %}
  - name: Debian9
    image: wilmardo/docker-debian-ansible:9
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /run/lock
{% endif %}

{%- if os == "Debian" and version == "jessie" %}
  - name: Debian8
    image: wilmardo/docker-debian-ansible:8
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /run/lock
{% endif %}

{%- if os == "Fedora" and version == "27" %}
  - name: Fedora27
    image: wilmardo/docker-fedora-ansible:27
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
{% endif %}

{%- if os == "Fedora" and version == "26" %}
  - name: Fedora26
    image: wilmardo/docker-fedora-ansible:26
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
{% endif %}

{%- if os == "Ubuntu" and version == "xenial" %}
  - name: Ubuntu1604
    image: wilmardo/docker-ubuntu-ansible:16.04
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /run/locks
{% endif %}
{%- endfor -%}
{%- endfor %}

provisioner:
  name: ansible
  options:
    v: true
  lint:
    name: ansible-lint

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
