---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: molecule/_rules/.yamllint

platforms:
{%- for os, versions in cookiecutter.platforms|dictsort %}
{%- for version in versions %}
{%- if os == "Alpine" and version == "3.5" %}
  - name: Alpine35
    image: lansible/alpine:3.5
{% endif %}

{%- if os == "Alpine" and version == "3.4" %}
  - name: Alpine34
    image: lansible/alpine:3.4
{% endif %}

{%- if os == "CentOS" and version == "7" %}
  - name: CentOS7
    image: lansible/centos:7
{% endif %}

{%- if os == "Debian" and version == "stretch" %}
  - name: Debian9
    image: lansible/debian:9
{% endif %}

{%- if os == "Debian" and version == "jessie" %}
  - name: Debian8
    image: lansible/debian:8
{% endif %}

{%- if os == "Fedora" and version == "27" %}
  - name: Fedora27
    image: lansible/fedora:27
{% endif %}

{%- if os == "Fedora" and version == "26" %}
  - name: Fedora26
    image: lansible/fedora:26
{% endif %}

{%- if os == "Ubuntu" and version == "xenial" %}
  - name: Ubuntu1604
    image: lansible/ubuntu:16.04
{% endif %}
{%- endfor -%}
{%- endfor %}
provisioner:
  name: ansible
  options:
    v: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  lint:
    name: ansible-lint
    options:
      c: molecule/_rules/.ansible-lint

scenario:
  name: default

verifier:
  name: goss
  enabled: false
