---
{% raw %}
- name: Install prerequisites with apt
  apt:
    name: "{{ {% endraw %}{{ cookiecutter.role_name }}{% raw %}_prerequisites }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install prerequisites with yum
  yum:
    name: "{{ {% endraw %}{{ cookiecutter.role_name }}{% raw %}_prerequisites }}"
    state: present
    update_cache: true
  when: ansible_distribution == "CentOS"

- name: Install prerequisites with dnf
  dnf:
    name: "{{ {% endraw %}{{ cookiecutter.role_name }}{% raw %}_prerequisites }}"
    state: present
  when: ansible_distribution == "Fedora"

- name: Install packages for Centos 6 to be able to validate SNI
  yum:
    name: "{{ {% endraw %}{{ cookiecutter.role_name }}{% raw %}_sni_packages }}"
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
{% endraw %}